### ISSUE TITLE
Data path

### ISSUE THREAD

**Issue by kxhit** [MegaScenes/nvs#2]
Hi thanks for contributing the large scale dataset!

In the [.pkl split,](https://github.com/MegaScenes/nvs?tab=readme-ov-file#dataset) the data path is something like this "['/share/phoenix/nfs05/S8/jt664/WikiSFM/data/main/images/Museo_Postale_e_Telegrafico_della_Mitteleuropa/commons/Museo_Postale_e_Telegrafico_della_Mitteleuropa/0/pictures/MuseoPoste 2.jpg']" but in the downloaded dataset [layout](https://github.com/MegaScenes/dataset?tab=readme-ov-file#dataset-layout), the data path is under some folders like "000".

So how to change it to the local path accordingly? I think [this part of code ](https://github.com/MegaScenes/nvs/blob/814af59853c2df056539b8cb294298dfa035605b/dataloader/paired_dataset.py#L57) doesn't work on the current dataset layout. Is there any guidance?

Or if I want to find the images with poses in each scene, e.g., 10 images for each scene with poses, not just 1-to-1 pair, how can I sort the dataset and get such scene instances?

Thank you!

**Comment by jot-jt** [comment]
Hi, thanks for the comments! We will update the `convert_path_to_your_path` function to make it easier to change.

---

To change the local path:

In the file path, the `{category}` (which is the scene name after `/images/` and before `/commons/`) can be replaced with the six-digit zero-padded scene-ID as described [here](https://github.com/MegaScenes/dataset?tab=readme-ov-file#scene-folders). [This JSON file](https://megascenes.s3.us-west-2.amazonaws.com/metadata/categories.json) maps the category name to the scene ID.

Furthermore, for the image name, all spaces should be replaced with underscores.

 Using the path you sent as an example, the path

```
/share/phoenix/nfs05/S8/jt664/WikiSFM/data/main/images/Museo_Postale_e_Telegrafico_della_Mitteleuropa/commons/Museo_Postale_e_Telegrafico_della_Mitteleuropa/0/pictures/MuseoPoste 2.jpg
```

should become something like

```
{your_megascenes_base_dir}/images/245/779/commons/Museo_Postale_e_Telegrafico_della_Mitteleuropa/0/pictures/MuseoPoste_2.jpg
```

since the category "Museo_Postale_e_Telegrafico_della_Mitteleuropa" has a scene ID of 245779.

---

As for finding images with poses in each scene:

We plan to write some tutorials in the future to help users extract this information. For now, here are some pointers:

In the [/reconstruct/](https://github.com/MegaScenes/dataset?tab=readme-ov-file#reconstruct-directory) folder, some scenes have one or more point cloud reconstructions. A reconstruction contains a `images.bin` file, which can be read into Python using [read_images_binary() in this standalone script](https://github.com/colmap/colmap/blob/c5c7b9c7cf2f34a7b102de29e356c103db8263be/scripts/python/read_write_model.py#L247). This function will read the `images.bin` file and return an dictionary that maps each image to some metadata, including a qvec (quaternion) and a tvec (translation). This qvec and tvec can be converted into an extrinsic matrix for the image. Then, the extrinsic matrix can be used to find the image position in world coordinates.

The conversion from qvec/tvec to coordinates is described [here](https://colmap.github.io/format.html#images-txt).
