### ISSUE TITLE
model.safetensors and pytorch_model.bin

### ISSUE THREAD

**Issue by jianglh-WHU** [MegaScenes/nvs#4]
Thanks for your excellent work.

I try to download the ckpt from s3://megascenes/nvs_checkpoints/warp_plus_pose/iter_112000/, and then run 
```python video_script.py -e configs/warp_plus_pose/ -r 112000 -i data/examples/audley_end_house.jpg -s qual_eval/warp_plus_pose/audley.```

However, I met an error in [accelerator.load_state(join(args.exp_dir, resume_folder))](https://github.com/MegaScenes/nvs/blob/0de3b004f643e0584112e7282a14ec304358e93f/video_script.py#L59), the reason is that pytorch_model.bin is not in that folder.
I solved the problem by converting the model.safetensors to pytorch_model.bin by
```
if "pytorch_model.bin" not in join(args.exp_dir, resume_folder):
    pt_state_dict = load_file(join(args.exp_dir, resume_folder,"model.safetensors"))
    torch.save(pt_state_dict,join(args.exp_dir, resume_folder,"pytorch_model.bin"))
```

**Comment by jianglh-WHU** [comment]
Emm, I use warp_plus_pose ckpt and get the result of audley, it's normal? Why every frame changes and lack of 3d consistency?
![best](https://github.com/user-attachments/assets/17f2aee2-b3cd-42ee-932f-6344584a29d3)

**Comment by jianglh-WHU** [comment]
It looks like not as robust as zeronvs_finetune, it's right?
![best](https://github.com/user-attachments/assets/4eaa7391-14c9-420d-9d4d-6eb087e9ad11)

**Comment by gene-chou** [comment]
Hey @jianglh-WHU thanks for bringing up the issue. We'll look into the checkpoints and see if we need to update them. 
You should be able to get much better results by adjusting the default camera path -- which in this case is probably too extreme for the model to handle. The finetuned zeronvs checkpoint is more "robust" because it may return the reference image (or an image very similar to it) when there is a large change in poses.
